name: "An amazing journey in Digitalization"
markdown: kramdown
title: "An amazing journey in Digitalization."
description: "My personal journey in data science, machine learning, deep learning, cognitive computing, data engineering and big data in this new digitalization era. Discovering the use of digital technologies to change a business model and provide new revenue and value-producing opportunities."
url: "https://pparacch.github.io"

gems:
  - jekyll-feed
  - jekyll-seo-tag
