name: "An amazing journey in Data Science"
markdown: kramdown
title: "An amazing journey in Data Science and Machine Learning."
description: "My personal journey in data science, machine learning, data engineering and big data while doing data science. Discovering the hidden value of data."
url: "https://pparacch.github.io"

gems:
  - jekyll-feed
  - jekyll-seo-tag
